### ISSUE TITLE
AWS Configure Not Match Onboarding Instructions

### ISSUE THREAD

**Issue by NicAtak** [Shift3/dj-starter#56]
https://shift3.github.io/dj-starter/docs/deploying-your-app/provisioning-infrastructure#quick-start
Onboarding [Google Doc](https://docs.google.com/document/d/1mUnHYB-lIOceWizZorNqr-XJI6cglJUpVa3XgjVt26E/edit) does not match the quickstart of the Dj-Starter
![Screenshot from 2023-03-30 15-34-06](https://user-images.githubusercontent.com/91444149/228978496-829b6c11-fd73-4f57-9103-ffdfee624647.png)

It does not include SSO session name, SSO start URL, SSO region, and SSO registration scopes

**Comment by NicAtak** [comment]
Hi Michael, 
What is the assignment? I see that the PR was merged. Is the new assignment for Kedest issue #212?

**Comment by michaelachrisco** [comment]
Im nots sure what your referring to? 

If its to this one, we are complete with this issue. Thanks again!

**Comment by NicAtak** [comment]
I received an email saying this was assigned to me so I was confused too

**Comment by michaelachrisco** [comment]
That was me. I assigned you to the issue since you worked on this. Usually when we assign someone to an issue, it means they are working/have worked on the issue it pertains to, if that makes sense.
