### ISSUE TITLE
Match Standard Issue templates to our other boilerplate projects

### ISSUE THREAD

**Issue by michaelachrisco** [Shift3/dj-starter#58]
## Expected Behavior

Within our other boilerplate projects, we include issue templates like so: 

- https://github.com/Shift3/boilerplate-client-react/tree/develop/.github/ISSUE_TEMPLATE 

- Also within our Standards and Practices: https://github.com/Shift3/standards-and-practices/tree/main/.github/ISSUE_TEMPLATE 

## Actual/Current Behavior
We have no standards of issues at the moment, so any new issues will manually have to put in the headers/concepts that we usually shortcut using our templates. 

If we include each one of these templates, we will reduce time/energy creating Bug reports/Feature requests/etc...that commonly pop up in repos.

**Comment by michaelachrisco** [comment]
Also to note, there is no `.github` folder and no templates within the cookie cutter project that get generated at time of run. Reference: https://github.com/Shift3/dj-starter/tree/main/%7B%7B%20cookiecutter.project_slug%20%7D%7D

**Comment by coreyshuman** [comment]
Nice find! I was just about to make an issue here for something else, so I would have encountered this and been annoyed. lol
