### ISSUE TITLE
AWS configuration does not fit the onboarding guidelines

### ISSUE THREAD

**Issue by tiruworktito** [Shift3/dj-starter#59]
![69f019fe-3b7c-45c8-a78d-89e76350c4f9](https://user-images.githubusercontent.com/89325936/229220950-c9c7dec0-a2a8-4c7e-853a-41421335a259.jpeg)
https://shift3.github.io/dj-starter/docs/getting-started/intro#quick-start
Google Doc's quickstart differs from Dj- Starter's. 

[onboarding[GoogleDoc]](https://docs.google.com/document/d/1mUnHYB-lIOceWizZorNqr-XJI6cglJUpVa3XgjVt26E/edit#heading=h.qvi8deze7yj7)

it does not include SSO session name SSO start URL, SSO region SSO registration scopes

**Comment by michaelachrisco** [comment]
Im going to close this issue as we have addressed this with @57.
