### ISSUE TITLE
AWS configure not much on boarding instructions

### ISSUE THREAD

**Issue by kedif** [Shift3/dj-starter#60]
https://shift3.github.io/dj-starter/docs/getting-started/intro#quick-start

on boarding [Google Doc ](https://docs.google.com/document/d/1mUnHYB-lIOceWizZorNqr-XJI6cglJUpVa3XgjVt26E/edit#heading=h.o4rx2vic9jt6)dose not much the quick start of the Dj-starter

it dose not include SSO start URL, SSO region, SSO registration scopes.

**Comment by michaelachrisco** [comment]
@kedif Thanks for adding that one. We figured this out on call/updating the doc. Closing this one out.
